version: "3.7"

networks:
  default:
    driver: bridge

services:
  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    volumes:
      - "./storage/minio:/s3"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: sh
    command: -c "minio server /s3 --console-address :9001"
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    ports:
      - "5432:5432"
  pgweb:
    restart: always 
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/library_management?sslmode=disable
    depends_on:
      - postgres
    links:
      - postgres  
  api:
    build: 
      context: .
      dockerfile: build/Dockerfile${CUSTOM}
    networks:
      - default
    ports: 
      - "8080:8080"
      - "4433:4433"
    depends_on:
      - minio
      - redis
      - postgres
    links:
      - minio
      - redis
      - postgres
    volumes:
      - ./:/app