version: "3.7"

networks:
  app:
    driver: bridge

services:
  redis:
    image: redis:alpine
    networks:
      - app
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app
    ports:
      - "5432:5432"

  api:
    build: 
      context: .
      dockerfile: build/Dockerfile
    networks:
      - app
    ports: 
      - "4242:8080"
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres