version: "3.7"

networks:
  default:
    driver: bridge

services:
  api:
    build: 
      context: .
      dockerfile: build/Dockerfile
    networks:
      - default
    ports: 
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    #volumes:
    #  - ./:/app
      
  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    ports:
      - "5432:5432"

  pgweb:
    restart: always 
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/library_management?sslmode=disable
    depends_on:
      - postgres
    links:
      - postgres  
