# Configuration vars for cmd/app
[app]
name = "LMS app"
port = ":8080"
idle-timeout = 5 # As seconds
print-routes = false
prefork = false
production = false

[app.tls]
enable = false
http2-support = false
cert-file = "./storage/selfsigned.crt"
key-file = "./storage/selfsigned.key"

[app.hash]
bcrypt-cost = 10 # min: 4, max: 31

[logger]
time-format = "" # https://pkg.go.dev/time#pkg-constants, https://github.com/rs/zerolog/blob/master/api.go#L10 
level = 0 # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true

[db.redis]
url = "redis://redis:6379/"
reset = false

[db.postgres]
host = "postgres"
port = 5432
name = "library_management"
user = "postgres"
password = "postgres"

[middleware.jwt]
secret = "UjXn2r5u8x/A?D(G+KbPeSgVkYp3s6v9"
hours = 5

[middleware.compress]
enable = true
level = 1

[middleware.recover]
enable = true

[middleware.monitor]
enable = true
path = "/monitor"

[middleware.pprof]
enable = false