[app]
port = 8080
production = false

[db.redis]
url = "redis://redis:6379/"
reset = false

[db.postgres]
host = "postgres"
port = 5432
name = "library_management"
user = "postgres"
password = "postgres"

[middleware.jwt]
secret = "UjXn2r5u8x/A?D(G+KbPeSgVkYp3s6v9"
hours = 5

[middleware.compress]
enable = true
level = 1

[middleware.recover]
enable = true