[app]
port = 8080
production = false

[db.redis]
url = "redis://redis:6379/"
reset = false

[db.postgres]
host = "postgres"
port = 5432
name = "library_management"
user = "postgres"
password = "postgres"