[app]
port = 8080
production = false

[db.redis]
url = "redis://127.0.0.1:6379/"
reset = false

[db.postgres]
host = "127.0.0.1"
port = 5423
name = "library_management"
user = "postgres"
password = "postgres"