on: [push, pull_request]
name: Run Tests
jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
    runs-on: ubuntu-latest
    services:
      redis:
        image: 'redis:latest'
        ports:
          - '6379:6379'
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Tests
        run: go test ./... -v -race